#pragma once
// Auto-generated by tools/generate_localization_bindings.ps1. Do not edit by hand.
#include <string>

struct LocalizationKeysAccessor
{
        const char* Get(const std::string& key) const;

        // Toggle me with %s
        inline const char* Toggle_me_with_s() const { return Get("Toggle me with %s"); }

        // Toggle Online with %s
        inline const char* Toggle_Online_with_s() const { return Get("Toggle Online with %s"); }

        // Toggle HUD with %s
        inline const char* Toggle_HUD_with_s() const { return Get("Toggle HUD with %s"); }

        // Generate Debug Logs
        inline const char* Generate_Debug_Logs() const { return Get("Generate Debug Logs"); }

        // Write DEBUG.txt with detailed runtime information. Saved to settings.ini for future sessions.
        inline const char* Write_DEBUG_txt_with_detailed_runtime_information_Saved_to_settings_ini_for_future_sessions() const { return Get("Write DEBUG.txt with detailed runtime information. Saved to settings.ini for future sessions."); }

        // Online
        inline const char* Online() const { return Get("Online"); }

        // Gameplay settings
        inline const char* Gameplay_settings() const { return Get("Gameplay settings"); }

        // Custom palettes
        inline const char* Custom_palettes() const { return Get("Custom palettes"); }

        // Hitbox overlay
        inline const char* Hitbox_overlay() const { return Get("Hitbox overlay"); }

        // FrameHistory
        inline const char* FrameHistory() const { return Get("FrameHistory"); }

        // Framedata
        inline const char* Framedata() const { return Get("Framedata"); }

        // Avatar settings
        inline const char* Avatar_settings() const { return Get("Avatar settings"); }

        // Controller Settings
        inline const char* Controller_Settings() const { return Get("Controller Settings"); }

        // Local Controller Override
        inline const char* Local_Controller_Override() const { return Get("Local Controller Override"); }

        // Choose which connected controller or the keyboard should be Player 1 and Player 2. Use Refresh when devices change.
        inline const char* Choose_which_connected_controller_or_the_keyboard_should_be_Player_1_and_Player_2_Use_Refresh_when_devices_change() const { return Get("Choose which connected controller or the keyboard should be Player 1 and Player 2. Use Refresh when devices change."); }

        // Refresh controllers
        inline const char* Refresh_controllers() const { return Get("Refresh controllers"); }

        // Reload the controller list and reinitialize input slots to match connected devices.
        inline const char* Reload_the_controller_list_and_reinitialize_input_slots_to_match_connected_devices() const { return Get("Reload the controller list and reinitialize input slots to match connected devices."); }

        // Open Joy.cpl
        inline const char* Open_Joy_cpl() const { return Get("Open Joy.cpl"); }

        // Auto-refresh
        inline const char* Auto_refresh() const { return Get("Auto-refresh"); }

        // Automatically refresh controller slots when devices change. The internal call to refresh controllers may freeze the game for a few moments, so only enable this if you are okay with short pauses.
        inline const char* Automatically_refresh_controller_slots_when_devices_change_The_internal_call_to_refresh_controllers_may_freeze_the_game_for_a_few_moments_so_only_enable_this_if_you_are_okay_with_short_pauses() const { return Get("Automatically refresh controller slots when devices change. The internal call to refresh controllers may freeze the game for a few moments, so only enable this if you are okay with short pauses."); }

        // No input devices detected.
        inline const char* No_input_devices_detected() const { return Get("No input devices detected."); }

        // STEAM INPUT: %s
        inline const char* STEAM_INPUT_s() const { return Get("STEAM INPUT: %s"); }

        // ON
        inline const char* ON() const { return Get("ON"); }

        // OFF
        inline const char* OFF() const { return Get("OFF"); }

        // Steam Input appears to be active.\nThis will disable some of this section's features.
        inline const char* Steam_Input_appears_to_be_active_This_will_disable_some_of_this_section_s_features() const { return Get("Steam Input appears to be active.\nThis will disable some of this section's features."); }

        // The internal behavior of Steam Input hides some controllers from the game's process, thus making some controller related features impossible/work in unintended ways.\n\nThe disabled features include:\n- Local Controller Override\n- Opening Joy.cpl
        inline const char* The_internal_behavior_of_Steam_Input_hides_some_controllers_from_the_game_s_process_thus_making_some_controller_related_features_impossible_work_in_unintended_ways_The_disabled_features_include_Local_Controller_Override_Opening_Joy_cpl() const { return Get("The internal behavior of Steam Input hides some controllers from the game's process, thus making some controller related features impossible/work in unintended ways.\n\nThe disabled features include:\n- Local Controller Override\n- Opening Joy.cpl"); }

        // Swap P1 Controller to P2
        inline const char* Swap_P1_Controller_to_P2() const { return Get("Swap P1 Controller to P2"); }

        // Changes P1 Controller's assignment so it is recognized as P2. Internally, this is just swapping p1 with p2's game controllers.
        inline const char* Changes_P1_Controller_s_assignment_so_it_is_recognized_as_P2_Internally_this_is_just_swapping_p1_with_p2_s_game_controllers() const { return Get("Changes P1 Controller's assignment so it is recognized as P2. Internally, this is just swapping p1 with p2's game controllers."); }

        // Multiple keyboards override
        inline const char* Multiple_keyboards_override() const { return Get("Multiple keyboards override"); }

        // Choose which physical keyboards should be treated as Player 1 when multiple keyboards are connected. All other keyboards will drive Player 2 using their saved mappings (defaults to WASD/JIKL).
        inline const char* Choose_which_physical_keyboards_should_be_treated_as_Player_1_when_multiple_keyboards_are_connected_All_other_keyboards_will_drive_Player_2_using_their_saved_mappings_defaults_to_WASD_JIKL() const { return Get("Choose which physical keyboards should be treated as Player 1 when multiple keyboards are connected. All other keyboards will drive Player 2 using their saved mappings (defaults to WASD/JIKL)."); }

        // No keyboards selected
        inline const char* No_keyboards_selected() const { return Get("No keyboards selected"); }

        // No keyboards detected.
        inline const char* No_keyboards_detected() const { return Get("No keyboards detected."); }

        // P1 Keyboards
        inline const char* P1_Keyboards() const { return Get("P1 Keyboards"); }

        // Map
        inline const char* Map() const { return Get("Map"); }

        // Rename
        inline const char* Rename() const { return Get("Rename"); }

        // Ignore
        inline const char* Ignore() const { return Get("Ignore"); }

        // Rename keyboard
        inline const char* Rename_keyboard() const { return Get("Rename keyboard"); }

        // Set a custom name for this keyboard.
        inline const char* Set_a_custom_name_for_this_keyboard() const { return Get("Set a custom name for this keyboard."); }

        // Save
        inline const char* Save() const { return Get("Save"); }

        // Cancel
        inline const char* Cancel() const { return Get("Cancel"); }

        // Clear
        inline const char* Clear() const { return Get("Clear"); }

        // Configure keyboard mapping
        inline const char* Configure_keyboard_mapping() const { return Get("Configure keyboard mapping"); }

        // Unbound
        inline const char* Unbound() const { return Get("Unbound"); }

        // Press a key...
        inline const char* Press_a_key() const { return Get("Press a key..."); }

        // Bind
        inline const char* Bind() const { return Get("Bind"); }

        // Menu action
        inline const char* Menu_action() const { return Get("Menu action"); }

        // Battle action
        inline const char* Battle_action() const { return Get("Battle action"); }

        // Close
        inline const char* Close() const { return Get("Close"); }

        // Set all to default
        inline const char* Set_all_to_default() const { return Get("Set all to default"); }

        // Ignored keyboards
        inline const char* Ignored_keyboards() const { return Get("Ignored keyboards"); }

        // No ignored keyboards.
        inline const char* No_ignored_keyboards() const { return Get("No ignored keyboards."); }

        // Unignore
        inline const char* Unignore() const { return Get("Unignore"); }

        // (connected)
        inline const char* connected() const { return Get("(connected)"); }

        // (not connected)
        inline const char* not_connected() const { return Get("(not connected)"); }

        // Mapping for %s
        inline const char* Mapping_for_s() const { return Get("Mapping for %s"); }

        // Test
        inline const char* Test() const { return Get("Test"); }

        // Player 1 Controller
        inline const char* Player_1_Controller() const { return Get("Player 1 Controller"); }

        // Player 2 Controller
        inline const char* Player_2_Controller() const { return Get("Player 2 Controller"); }

        // Loaded settings.ini values
        inline const char* Loaded_settings_ini_values() const { return Get("Loaded settings.ini values"); }

        // Current online players:
        inline const char* Current_online_players() const { return Get("Current online players:"); }

        // <No data>
        inline const char* No_data() const { return Get("<No data>"); }

        // Avatar
        inline const char* Avatar() const { return Get("Avatar"); }

        // Color
        inline const char* Color() const { return Get("Color"); }

        // Accessory 1
        inline const char* Accessory_1() const { return Get("Accessory 1"); }

        // Accessory 2
        inline const char* Accessory_2() const { return Get("Accessory 2"); }

        // CONNECT TO NETWORK MODE FIRST
        inline const char* CONNECT_TO_NETWORK_MODE_FIRST() const { return Get("CONNECT TO NETWORK MODE FIRST"); }

        // FrameHistory help
        inline const char* FrameHistory_help() const { return Get("FrameHistory help"); }

        // FrameHistory auto reset help
        inline const char* FrameHistory_auto_reset_help() const { return Get("FrameHistory auto reset help"); }

        // Box width
        inline const char* Box_width() const { return Get("Box width"); }

        // Box height
        inline const char* Box_height() const { return Get("Box height"); }

        // spacing
        inline const char* spacing() const { return Get("spacing"); }

        // Enable##framehistory_section
        inline const char* Enable_framehistory_section() const { return Get("Enable##framehistory_section"); }

        // Auto Reset##Reset after each idle frame
        inline const char* Auto_Reset_Reset_after_each_idle_frame() const { return Get("Auto Reset##Reset after each idle frame"); }

        // Enable##framedata_section
        inline const char* Enable_framedata_section() const { return Get("Enable##framedata_section"); }

        // Advantage on stagger hit
        inline const char* Advantage_on_stagger_hit() const { return Get("Advantage on stagger hit"); }

        // YOU ARE NOT IN MATCH!
        inline const char* YOU_ARE_NOT_IN_MATCH() const { return Get("YOU ARE NOT IN MATCH!"); }

        // YOU ARE NOT IN TRAINING MODE OR REPLAY THEATER!
        inline const char* YOU_ARE_NOT_IN_TRAINING_MODE_OR_REPLAY_THEATER() const { return Get("YOU ARE NOT IN TRAINING MODE OR REPLAY THEATER!"); }

        // YOU ARE NOT IN A MATCH, IN TRAINING MODE OR REPLAY THEATER!
        inline const char* YOU_ARE_NOT_IN_A_MATCH_IN_TRAINING_MODE_OR_REPLAY_THEATER() const { return Get("YOU ARE NOT IN A MATCH, IN TRAINING MODE OR REPLAY THEATER!"); }

        // THERE WAS AN ERROR LOADING ONE/BOTH OF THE CHARACTERS
        inline const char* THERE_WAS_AN_ERROR_LOADING_ONE_BOTH_OF_THE_CHARACTERS() const { return Get("THERE WAS AN ERROR LOADING ONE/BOTH OF THE CHARACTERS"); }

        // Palette editor
        inline const char* Palette_editor() const { return Get("Palette editor"); }

        // YOU ARE NOT IN MATCH! (Replay)
        inline const char* YOU_ARE_NOT_IN_MATCH_Replay() const { return Get("YOU ARE NOT IN MATCH! (Replay)"); }

        // YOU ARE NOT IN REPLAY MENU!
        inline const char* YOU_ARE_NOT_IN_REPLAY_MENU() const { return Get("YOU ARE NOT IN REPLAY MENU!"); }

        // YOU ARE NOT IN CHARACTER SELECTION!
        inline const char* YOU_ARE_NOT_IN_CHARACTER_SELECTION() const { return Get("YOU ARE NOT IN CHARACTER SELECTION!"); }

        // Hide HUD
        inline const char* Hide_HUD() const { return Get("Hide HUD"); }

        // Toggle Rewind
        inline const char* Toggle_Rewind() const { return Get("Toggle Rewind"); }

        // Replay Database
        inline const char* Replay_Database() const { return Get("Replay Database"); }

        // Enable/Disable Automatic Replay Uploads?
        inline const char* Enable_Disable_Automatic_Replay_Uploads() const { return Get("Enable/Disable Automatic Replay Uploads?"); }

        // Main window notification format
        inline const char* Main_window_notification_format() const { return Get("Main window notification format"); }

        // IM BOBLEIS can automatically upload your replays to a public central repository.\n\nThis feature allows:\n- Easy sharing: Facilitates sharing of replays between players.\n- Community sharing: Contribute to a collection of matches for learning and analysis.\n- Cataloging: Easily search by characters for matchups.\n- Storage: Keep your replays backed up automatically after the 100 limit.\n\nYou can access the database using the Replay Database button on the IM main menu.\n\nIf you disable it your replays won't be uploaded even if matched with someone with it enabled.\n\nIf you wish to turn it off/on again you can access this menu using the button on the IM main menu or using settings.ini.\n\nThis has no impact on performance or stability.\n\nWould you like to leave automatic replay uploads on or turn it off?
        inline const char* IM_BOBLEIS_can_automatically_upload_your_replays_to_a_public_central_repository_This_feature_allows_Easy_sharing_Facilitates_sharing_of_replays_between_players_Community_sharing_Contribute_to_a_collection_of_matches_for_learning_and_analysis_Cataloging_Easily_search_by_characters_for_matchups_Storage_Keep_your_replays_backed_up_automatically_after_the_100_limit_You_can_access_the_database_using_the_Replay_Database_button_on_the_IM_main_menu_If_you_disable_it_your_replays_won_t_be_uploaded_even_if_matched_with_someone_with_it_enabled_If_you_wish_to_turn_it_off_on_again_you_can_access_this_menu_using_the_button_on_the_IM_main_menu_or_using_settings_ini_This_has_no_impact_on_performance_or_stability_Would_you_like_to_leave_automatic_replay_uploads_on_or_turn_it_off() const { return Get("IM BOBLEIS can automatically upload your replays to a public central repository.\n\nThis feature allows:\n- Easy sharing: Facilitates sharing of replays between players.\n- Community sharing: Contribute to a collection of matches for learning and analysis.\n- Cataloging: Easily search by characters for matchups.\n- Storage: Keep your replays backed up automatically after the 100 limit.\n\nYou can access the database using the Replay Database button on the IM main menu.\n\nIf you disable it your replays won't be uploaded even if matched with someone with it enabled.\n\nIf you wish to turn it off/on again you can access this menu using the button on the IM main menu or using settings.ini.\n\nThis has no impact on performance or stability.\n\nWould you like to leave automatic replay uploads on or turn it off?"); }

        // Enable/Disable Upload
        inline const char* Enable_Disable_Upload() const { return Get("Enable/Disable Upload"); }

        // Discord
        inline const char* Discord() const { return Get("Discord"); }

        // Forum
        inline const char* Forum() const { return Get("Forum"); }

        // GitHub
        inline const char* GitHub() const { return Get("GitHub"); }

        // Player1
        inline const char* Player1() const { return Get("Player1"); }

        // Player2
        inline const char* Player2() const { return Get("Player2"); }

        // Draw hitbox/hurtbox
        inline const char* Draw_hitbox_hurtbox() const { return Get("Draw hitbox/hurtbox"); }

        // Draw origin
        inline const char* Draw_origin() const { return Get("Draw origin"); }

        // Draw collision
        inline const char* Draw_collision() const { return Get("Draw collision"); }

        // Draw throw/range boxes
        inline const char* Draw_throw_range_boxes() const { return Get("Draw throw/range boxes"); }

        // The point in space where your character resides. \nImportant!: This is a single point, the render is composed of two lines to facilitate viewing, the actual point is where the two lines touch.
        inline const char* The_point_in_space_where_your_character_resides_Important_This_is_a_single_point_the_render_is_composed_of_two_lines_to_facilitate_viewing_the_actual_point_is_where_the_two_lines_touch() const { return Get("The point in space where your character resides. \nImportant!: This is a single point, the render is composed of two lines to facilitate viewing, the actual point is where the two lines touch."); }

        // Defines collision between objects/characters. Also used for throw range checks.
        inline const char* Defines_collision_between_objects_characters_Also_used_for_throw_range_checks() const { return Get("Defines collision between objects/characters. Also used for throw range checks."); }

        // Throw range help
        inline const char* Throw_range_help() const { return Get("Throw range help"); }

        // Freeze frame:
        inline const char* Freeze_frame() const { return Get("Freeze frame:"); }

        // Frame Count
        inline const char* Frame_Count() const { return Get("Frame Count"); }

        // Reset
        inline const char* Reset() const { return Get("Reset"); }

        // Freeze animation
        inline const char* Freeze_animation() const { return Get("Freeze animation"); }

        // Stop timer
        inline const char* Stop_timer() const { return Get("Stop timer"); }

        // Step frames
        inline const char* Step_frames() const { return Get("Step frames"); }

        // YOU ARE NOT IN TRAINING, VERSUS, OR REPLAY!
        inline const char* YOU_ARE_NOT_IN_TRAINING_VERSUS_OR_REPLAY() const { return Get("YOU ARE NOT IN TRAINING, VERSUS, OR REPLAY!"); }

        // Game Mode
        inline const char* Game_Mode() const { return Get("Game Mode"); }

        // Enable##hitbox_overlay_section
        inline const char* Enable_hitbox_overlay_section() const { return Get("Enable##hitbox_overlay_section"); }

        // Custom palette reload
        inline const char* Custom_palette_reload() const { return Get("Custom palette reload"); }

        // Enable##framehistory_section checkbox
        inline const char* Enable_framehistory_section_checkbox() const { return Get("Enable##framehistory_section checkbox"); }

        // Draw hitbox/hurtbox##hitbox_overlay_section
        inline const char* Draw_hitbox_hurtbox_hitbox_overlay_section() const { return Get("Draw hitbox/hurtbox##hitbox_overlay_section"); }

        // Draw origin##hitbox_overlay_section
        inline const char* Draw_origin_hitbox_overlay_section() const { return Get("Draw origin##hitbox_overlay_section"); }

        // Draw collision##hitbox_overlay_section
        inline const char* Draw_collision_hitbox_overlay_section() const { return Get("Draw collision##hitbox_overlay_section"); }

        // Step frames##hitbox_overlay_section
        inline const char* Step_frames_hitbox_overlay_section() const { return Get("Step frames##hitbox_overlay_section"); }

        // Gameplay settings header
        inline const char* Gameplay_settings_header() const { return Get("Gameplay settings header"); }

        // Hide HUD checkbox
        inline const char* Hide_HUD_checkbox() const { return Get("Hide HUD checkbox"); }

        // States
        inline const char* States() const { return Get("States"); }

        // Log
        inline const char* Log() const { return Get("Log"); }

        // Replay Rewind
        inline const char* Replay_Rewind() const { return Get("Replay Rewind"); }

        // Replay Upload
        inline const char* Replay_Upload() const { return Get("Replay Upload"); }

        // Enable##framehistory_section label
        inline const char* Enable_framehistory_section_label() const { return Get("Enable##framehistory_section label"); }

        // Auto Reset label
        inline const char* Auto_Reset_label() const { return Get("Auto Reset label"); }

        // FrameHistory width label
        inline const char* FrameHistory_width_label() const { return Get("FrameHistory width label"); }

        // FrameHistory height label
        inline const char* FrameHistory_height_label() const { return Get("FrameHistory height label"); }

        // FrameHistory spacing label
        inline const char* FrameHistory_spacing_label() const { return Get("FrameHistory spacing label"); }

        // FrameHistory not enabled message
        inline const char* FrameHistory_not_enabled_message() const { return Get("FrameHistory not enabled message"); }

        // FrameHistory character load error
        inline const char* FrameHistory_character_load_error() const { return Get("FrameHistory character load error"); }

        // Language
        inline const char* Language() const { return Get("Language"); }

        // Language incomplete label
        inline const char* Language_incomplete_label() const { return Get("Language incomplete label"); }

        // Language selection help
        inline const char* Language_selection_help() const { return Get("Language selection help"); }

        // KoreWaTestoDakeDa
        inline const char* KoreWaTestoDakeDa() const { return Get("KoreWaTestoDakeDa"); }

        // Refresh
        inline const char* Refresh() const { return Get("Refresh"); }

        // Recording side: %c
        inline const char* Recording_side_c() const { return Get("Recording side: %c"); }

        // Switch recording side
        inline const char* Switch_recording_side() const { return Get("Switch recording side"); }

        // Add/Remove
        inline const char* Add_Remove() const { return Get("Add/Remove"); }

        // Frame
        inline const char* Frame() const { return Get("Frame"); }

        // Literal
        inline const char* Literal() const { return Get("Literal"); }

        // Command
        inline const char* Command() const { return Get("Command"); }

        // Edit Input
        inline const char* Edit_Input() const { return Get("Edit Input"); }

        // Save
        inline const char* Save() const { return Get("Save"); }

        // Direction
        inline const char* Direction() const { return Get("Direction"); }

        // OK
        inline const char* OK() const { return Get("OK"); }

        // Player 1:
        inline const char* Player_1_() const { return Get("Player 1:"); }

        // Player 2:
        inline const char* Player_2_() const { return Get("Player 2:"); }

        // Select game mode:
        inline const char* Select_game_mode_() const { return Get("Select game mode:"); }

        // Copy to clipboard
        inline const char* Copy_to_clipboard() const { return Get("Copy to clipboard"); }

        // Search
        inline const char* Search() const { return Get("Search"); }

        // [system] Log has been copied to clipboard\n
        inline const char* system_Log_has_been_copied_to_clipboard_n() const { return Get("[system] Log has been copied to clipboard\n"); }

        // Stage
        inline const char* Stage() const { return Get("Stage"); }

        // Reload custom palettes
        inline const char* Reload_custom_palettes() const { return Get("Reload custom palettes"); }

        // Select character
        inline const char* Select_character() const { return Get("Select character"); }

        // Select palette
        inline const char* Select_palette() const { return Get("Select palette"); }

        // Select file
        inline const char* Select_file() const { return Get("Select file"); }

        // Gradient generator
        inline const char* Gradient_generator() const { return Get("Gradient generator"); }

        // Undo
        inline const char* Undo() const { return Get("Undo"); }

        // Redo
        inline const char* Redo() const { return Get("Redo"); }

        // Cannot save with Highlight mode on!
        inline const char* Cannot_save_with_Highlight_mode_on() const { return Get("Cannot save with Highlight mode on!"); }

        // Save with bloom effect
        inline const char* Save_with_bloom_effect() const { return Get("Save with bloom effect"); }

        // Bloom effects cannot be changed until a new round is started
        inline const char* Bloom_effects_cannot_be_changed_until_a_new_round_is_started() const { return Get("Bloom effects cannot be changed until a new round is started"); }

        // Palette name:
        inline const char* Palette_name_() const { return Get("Palette name:"); }

        // Creator (optional):
        inline const char* Creator_optional_() const { return Get("Creator (optional):"); }

        // Palette description (optional):
        inline const char* Palette_description_optional_() const { return Get("Palette description (optional):"); }

        // Save palette
        inline const char* Save_palette() const { return Get("Save palette"); }

        // Error, no filename given
        inline const char* Error_no_filename_given() const { return Get("Error, no filename given"); }

        // Error, not a valid filename
        inline const char* Error_not_a_valid_filename() const { return Get("Error, not a valid filename"); }

        // '%s' saved successfully
        inline const char* _s_saved_successfully() const { return Get("'%s' saved successfully"); }

        // '%s' save failed
        inline const char* _s_save_failed() const { return Get("'%s' save failed"); }

        // '%s' already exists.\nAre you sure you want to overwrite it?\n\n
        inline const char* _s_already_exists_Are_you_sure_you_want_to_overwrite_it_n_n() const { return Get("'%s' already exists.\nAre you sure you want to overwrite it?\n\n"); }

        // Reset palette
        inline const char* Reset_palette() const { return Get("Reset palette"); }

        // Out of bounds
        inline const char* Out_of_bounds() const { return Get("Out of bounds"); }

        // ONLINE PALETTE
        inline const char* ONLINE_PALETTE() const { return Get("ONLINE PALETTE"); }

        // Creator: %s
        inline const char* Creator_s() const { return Get("Creator: %s"); }

        // Description: %s
        inline const char* Description_s() const { return Get("Description: %s"); }

        // Has bloom effect
        inline const char* Has_bloom_effect() const { return Get("Has bloom effect"); }

        // Random selection
        inline const char* Random_selection() const { return Get("Random selection"); }

        // Start index
        inline const char* Start_index() const { return Get("Start index"); }

        // End index
        inline const char* End_index() const { return Get("End index"); }

        // Start color
        inline const char* Start_color() const { return Get("Start color"); }

        // End color
        inline const char* End_color() const { return Get("End color"); }

        // Swap colors
        inline const char* Swap_colors() const { return Get("Swap colors"); }

        // Generate gradient
        inline const char* Generate_gradient() const { return Get("Generate gradient"); }

        // Player 1
        inline const char* Player_1() const { return Get("Player 1"); }

        // Gap:
        inline const char* Gap_() const { return Get("Gap:"); }

        // Advantage:
        inline const char* Advantage_() const { return Get("Advantage:"); }

        // Player 2
        inline const char* Player_2() const { return Get("Player 2"); }
};


