#pragma once
// Auto-generated by tools/generate_localization_bindings.ps1. Do not edit by hand.
#include <string>

struct LocalizationKeysAccessor
{
        const char* Get(const std::string& key) const;

        // Toggle me with %s
        inline const char* Toggle_me_with_s() const { return Get("Toggle me with %s"); }

        // Toggle Online with %s
        inline const char* Toggle_Online_with_s() const { return Get("Toggle Online with %s"); }

        // Toggle HUD with %s
        inline const char* Toggle_HUD_with_s() const { return Get("Toggle HUD with %s"); }

        // Generate Debug Logs
        inline const char* Generate_Debug_Logs() const { return Get("Generate Debug Logs"); }

        // Write DEBUG.txt with detailed runtime information. Saved to settings.ini for future sessions.
        inline const char* Write_DEBUG_txt_with_detailed_runtime_information_Saved_to_settings_ini_for_future_sessions() const { return Get("Write DEBUG.txt with detailed runtime information. Saved to settings.ini for future sessions."); }

        // Online
        inline const char* Online() const { return Get("Online"); }

        // Gameplay settings
        inline const char* Gameplay_settings() const { return Get("Gameplay settings"); }

        // Custom palettes
        inline const char* Custom_palettes() const { return Get("Custom palettes"); }

        // Hitbox overlay
        inline const char* Hitbox_overlay() const { return Get("Hitbox overlay"); }

        // FrameHistory
        inline const char* FrameHistory() const { return Get("FrameHistory"); }

        // Framedata
        inline const char* Framedata() const { return Get("Framedata"); }

        // Avatar settings
        inline const char* Avatar_settings() const { return Get("Avatar settings"); }

        // Controller Settings
        inline const char* Controller_Settings() const { return Get("Controller Settings"); }

        // Local Controller Override
        inline const char* Local_Controller_Override() const { return Get("Local Controller Override"); }

        // Choose which connected controller or the keyboard should be Player 1 and Player 2. Use Refresh when devices change.
        inline const char* Choose_which_connected_controller_or_the_keyboard_should_be_Player_1_and_Player_2_Use_Refresh_when_devices_change() const { return Get("Choose which connected controller or the keyboard should be Player 1 and Player 2. Use Refresh when devices change."); }

        // Refresh controllers
        inline const char* Refresh_controllers() const { return Get("Refresh controllers"); }

        // Reload the controller list and reinitialize input slots to match connected devices.
        inline const char* Reload_the_controller_list_and_reinitialize_input_slots_to_match_connected_devices() const { return Get("Reload the controller list and reinitialize input slots to match connected devices."); }

        // Open Joy.cpl
        inline const char* Open_Joy_cpl() const { return Get("Open Joy.cpl"); }

        // Auto-refresh
        inline const char* Auto_refresh() const { return Get("Auto-refresh"); }

        // Automatically refresh controller slots when devices change. The internal call to refresh controllers may freeze the game for a few moments, so only enable this if you are okay with short pauses.
        inline const char* Automatically_refresh_controller_slots_when_devices_change_The_internal_call_to_refresh_controllers_may_freeze_the_game_for_a_few_moments_so_only_enable_this_if_you_are_okay_with_short_pauses() const { return Get("Automatically refresh controller slots when devices change. The internal call to refresh controllers may freeze the game for a few moments, so only enable this if you are okay with short pauses."); }

        // No input devices detected.
        inline const char* No_input_devices_detected() const { return Get("No input devices detected."); }

        // STEAM INPUT: %s
        inline const char* STEAM_INPUT_s() const { return Get("STEAM INPUT: %s"); }

        // ON
        inline const char* ON() const { return Get("ON"); }

        // OFF
        inline const char* OFF() const { return Get("OFF"); }

        // Steam Input appears to be active.\nThis will disable some of this section's features.
        inline const char* Steam_Input_appears_to_be_active_This_will_disable_some_of_this_section_s_features() const { return Get("Steam Input appears to be active.\nThis will disable some of this section's features."); }

        // The internal behavior of Steam Input hides some controllers from the game's process, thus making some controller related features impossible/work in unintended ways.\n\nThe disabled features include:\n- Local Controller Override\n- Opening Joy.cpl
        inline const char* The_internal_behavior_of_Steam_Input_hides_some_controllers_from_the_game_s_process_thus_making_some_controller_related_features_impossible_work_in_unintended_ways_The_disabled_features_include_Local_Controller_Override_Opening_Joy_cpl() const { return Get("The internal behavior of Steam Input hides some controllers from the game's process, thus making some controller related features impossible/work in unintended ways.\n\nThe disabled features include:\n- Local Controller Override\n- Opening Joy.cpl"); }

        // Swap P1 Controller to P2
        inline const char* Swap_P1_Controller_to_P2() const { return Get("Swap P1 Controller to P2"); }

        // Changes P1 Controller's assignment so it is recognized as P2. Internally, this is just swapping p1 with p2's game controllers.
        inline const char* Changes_P1_Controller_s_assignment_so_it_is_recognized_as_P2_Internally_this_is_just_swapping_p1_with_p2_s_game_controllers() const { return Get("Changes P1 Controller's assignment so it is recognized as P2. Internally, this is just swapping p1 with p2's game controllers."); }

        // Multiple keyboards override
        inline const char* Multiple_keyboards_override() const { return Get("Multiple keyboards override"); }

        // Choose which physical keyboards should be treated as Player 1 when multiple keyboards are connected. All other keyboards will drive Player 2 using their saved mappings (defaults to WASD/JIKL).
        inline const char* Choose_which_physical_keyboards_should_be_treated_as_Player_1_when_multiple_keyboards_are_connected_All_other_keyboards_will_drive_Player_2_using_their_saved_mappings_defaults_to_WASD_JIKL() const { return Get("Choose which physical keyboards should be treated as Player 1 when multiple keyboards are connected. All other keyboards will drive Player 2 using their saved mappings (defaults to WASD/JIKL)."); }

        // No keyboards selected
        inline const char* No_keyboards_selected() const { return Get("No keyboards selected"); }

        // No keyboards detected.
        inline const char* No_keyboards_detected() const { return Get("No keyboards detected."); }

        // P1 Keyboards
        inline const char* P1_Keyboards() const { return Get("P1 Keyboards"); }

        // Map
        inline const char* Map() const { return Get("Map"); }

        // Rename
        inline const char* Rename() const { return Get("Rename"); }

        // Ignore
        inline const char* Ignore() const { return Get("Ignore"); }

        // Rename keyboard
        inline const char* Rename_keyboard() const { return Get("Rename keyboard"); }

        // Set a custom name for this keyboard.
        inline const char* Set_a_custom_name_for_this_keyboard() const { return Get("Set a custom name for this keyboard."); }

        // Save
        inline const char* Save() const { return Get("Save"); }

        // Cancel
        inline const char* Cancel() const { return Get("Cancel"); }

        // Clear
        inline const char* Clear() const { return Get("Clear"); }

        // Configure keyboard mapping
        inline const char* Configure_keyboard_mapping() const { return Get("Configure keyboard mapping"); }

        // Unbound
        inline const char* Unbound() const { return Get("Unbound"); }

        // Press a key...
        inline const char* Press_a_key() const { return Get("Press a key..."); }

        // Bind
        inline const char* Bind() const { return Get("Bind"); }

        // Menu action
        inline const char* Menu_action() const { return Get("Menu action"); }

        // Battle action
        inline const char* Battle_action() const { return Get("Battle action"); }

        // Close
        inline const char* Close() const { return Get("Close"); }

        // Set all to default
        inline const char* Set_all_to_default() const { return Get("Set all to default"); }

        // Ignored keyboards
        inline const char* Ignored_keyboards() const { return Get("Ignored keyboards"); }

        // No ignored keyboards.
        inline const char* No_ignored_keyboards() const { return Get("No ignored keyboards."); }

        // Unignore
        inline const char* Unignore() const { return Get("Unignore"); }

        // (connected)
        inline const char* connected() const { return Get("(connected)"); }

        // (not connected)
        inline const char* not_connected() const { return Get("(not connected)"); }

        // Mapping for %s
        inline const char* Mapping_for_s() const { return Get("Mapping for %s"); }

        // Test
        inline const char* Test() const { return Get("Test"); }

        // Player 1 Controller
        inline const char* Player_1_Controller() const { return Get("Player 1 Controller"); }

        // Player 2 Controller
        inline const char* Player_2_Controller() const { return Get("Player 2 Controller"); }

        // Loaded settings.ini values
        inline const char* Loaded_settings_ini_values() const { return Get("Loaded settings.ini values"); }

        // Current online players:
        inline const char* Current_online_players() const { return Get("Current online players:"); }

        // <No data>
        inline const char* No_data() const { return Get("<No data>"); }

        // Avatar
        inline const char* Avatar() const { return Get("Avatar"); }

        // Color
        inline const char* Color() const { return Get("Color"); }

        // Accessory 1
        inline const char* Accessory_1() const { return Get("Accessory 1"); }

        // Accessory 2
        inline const char* Accessory_2() const { return Get("Accessory 2"); }

        // CONNECT TO NETWORK MODE FIRST
        inline const char* CONNECT_TO_NETWORK_MODE_FIRST() const { return Get("CONNECT TO NETWORK MODE FIRST"); }

        // FrameHistory help
        inline const char* FrameHistory_help() const { return Get("FrameHistory help"); }

        // FrameHistory auto reset help
        inline const char* FrameHistory_auto_reset_help() const { return Get("FrameHistory auto reset help"); }

        // Box width
        inline const char* Box_width() const { return Get("Box width"); }

        // Box height
        inline const char* Box_height() const { return Get("Box height"); }

        // spacing
        inline const char* spacing() const { return Get("spacing"); }

        // Enable##framehistory_section
        inline const char* Enable_framehistory_section() const { return Get("Enable##framehistory_section"); }

        // Auto Reset##Reset after each idle frame
        inline const char* Auto_Reset_Reset_after_each_idle_frame() const { return Get("Auto Reset##Reset after each idle frame"); }

        // Enable##framedata_section
        inline const char* Enable_framedata_section() const { return Get("Enable##framedata_section"); }

        // Advantage on stagger hit
        inline const char* Advantage_on_stagger_hit() const { return Get("Advantage on stagger hit"); }

        // YOU ARE NOT IN MATCH!
        inline const char* YOU_ARE_NOT_IN_MATCH() const { return Get("YOU ARE NOT IN MATCH!"); }

        // YOU ARE NOT IN TRAINING MODE OR REPLAY THEATER!
        inline const char* YOU_ARE_NOT_IN_TRAINING_MODE_OR_REPLAY_THEATER() const { return Get("YOU ARE NOT IN TRAINING MODE OR REPLAY THEATER!"); }

        // YOU ARE NOT IN A MATCH, IN TRAINING MODE OR REPLAY THEATER!
        inline const char* YOU_ARE_NOT_IN_A_MATCH_IN_TRAINING_MODE_OR_REPLAY_THEATER() const { return Get("YOU ARE NOT IN A MATCH, IN TRAINING MODE OR REPLAY THEATER!"); }

        // THERE WAS AN ERROR LOADING ONE/BOTH OF THE CHARACTERS
        inline const char* THERE_WAS_AN_ERROR_LOADING_ONE_BOTH_OF_THE_CHARACTERS() const { return Get("THERE WAS AN ERROR LOADING ONE/BOTH OF THE CHARACTERS"); }

        // Palette editor
        inline const char* Palette_editor() const { return Get("Palette editor"); }

        // YOU ARE NOT IN MATCH! (Replay)
        inline const char* YOU_ARE_NOT_IN_MATCH_Replay() const { return Get("YOU ARE NOT IN MATCH! (Replay)"); }

        // YOU ARE NOT IN REPLAY MENU!
        inline const char* YOU_ARE_NOT_IN_REPLAY_MENU() const { return Get("YOU ARE NOT IN REPLAY MENU!"); }

        // YOU ARE NOT IN CHARACTER SELECTION!
        inline const char* YOU_ARE_NOT_IN_CHARACTER_SELECTION() const { return Get("YOU ARE NOT IN CHARACTER SELECTION!"); }

        // Hide HUD
        inline const char* Hide_HUD() const { return Get("Hide HUD"); }

        // Toggle Rewind
        inline const char* Toggle_Rewind() const { return Get("Toggle Rewind"); }

        // Replay Database
        inline const char* Replay_Database() const { return Get("Replay Database"); }

        // Enable/Disable Upload
        inline const char* Enable_Disable_Upload() const { return Get("Enable/Disable Upload"); }

        // Discord
        inline const char* Discord() const { return Get("Discord"); }

        // Forum
        inline const char* Forum() const { return Get("Forum"); }

        // GitHub
        inline const char* GitHub() const { return Get("GitHub"); }

        // Player1
        inline const char* Player1() const { return Get("Player1"); }

        // Player2
        inline const char* Player2() const { return Get("Player2"); }

        // Draw hitbox/hurtbox
        inline const char* Draw_hitbox_hurtbox() const { return Get("Draw hitbox/hurtbox"); }

        // Draw origin
        inline const char* Draw_origin() const { return Get("Draw origin"); }

        // Draw collision
        inline const char* Draw_collision() const { return Get("Draw collision"); }

        // Draw throw/range boxes
        inline const char* Draw_throw_range_boxes() const { return Get("Draw throw/range boxes"); }

        // The point in space where your character resides. \nImportant!: This is a single point, the render is composed of two lines to facilitate viewing, the actual point is where the two lines touch.
        inline const char* The_point_in_space_where_your_character_resides_Important_This_is_a_single_point_the_render_is_composed_of_two_lines_to_facilitate_viewing_the_actual_point_is_where_the_two_lines_touch() const { return Get("The point in space where your character resides. \nImportant!: This is a single point, the render is composed of two lines to facilitate viewing, the actual point is where the two lines touch."); }

        // Defines collision between objects/characters. Also used for throw range checks.
        inline const char* Defines_collision_between_objects_characters_Also_used_for_throw_range_checks() const { return Get("Defines collision between objects/characters. Also used for throw range checks."); }

        // Throw range help
        inline const char* Throw_range_help() const { return Get("Throw range help"); }

        // Freeze frame:
        inline const char* Freeze_frame() const { return Get("Freeze frame:"); }

        // Frame Count
        inline const char* Frame_Count() const { return Get("Frame Count"); }

        // Reset
        inline const char* Reset() const { return Get("Reset"); }

        // Freeze animation
        inline const char* Freeze_animation() const { return Get("Freeze animation"); }

        // Stop timer
        inline const char* Stop_timer() const { return Get("Stop timer"); }

        // Step frames
        inline const char* Step_frames() const { return Get("Step frames"); }

        // YOU ARE NOT IN TRAINING, VERSUS, OR REPLAY!
        inline const char* YOU_ARE_NOT_IN_TRAINING_VERSUS_OR_REPLAY() const { return Get("YOU ARE NOT IN TRAINING, VERSUS, OR REPLAY!"); }

        // Game Mode
        inline const char* Game_Mode() const { return Get("Game Mode"); }

        // Enable##hitbox_overlay_section
        inline const char* Enable_hitbox_overlay_section() const { return Get("Enable##hitbox_overlay_section"); }

        // Custom palette reload
        inline const char* Custom_palette_reload() const { return Get("Custom palette reload"); }

        // Enable##framehistory_section checkbox
        inline const char* Enable_framehistory_section_checkbox() const { return Get("Enable##framehistory_section checkbox"); }

        // Draw hitbox/hurtbox##hitbox_overlay_section
        inline const char* Draw_hitbox_hurtbox_hitbox_overlay_section() const { return Get("Draw hitbox/hurtbox##hitbox_overlay_section"); }

        // Draw origin##hitbox_overlay_section
        inline const char* Draw_origin_hitbox_overlay_section() const { return Get("Draw origin##hitbox_overlay_section"); }

        // Draw collision##hitbox_overlay_section
        inline const char* Draw_collision_hitbox_overlay_section() const { return Get("Draw collision##hitbox_overlay_section"); }

        // Step frames##hitbox_overlay_section
        inline const char* Step_frames_hitbox_overlay_section() const { return Get("Step frames##hitbox_overlay_section"); }

        // Gameplay settings header
        inline const char* Gameplay_settings_header() const { return Get("Gameplay settings header"); }

        // Hide HUD checkbox
        inline const char* Hide_HUD_checkbox() const { return Get("Hide HUD checkbox"); }

        // States
        inline const char* States() const { return Get("States"); }

        // Log
        inline const char* Log() const { return Get("Log"); }

        // Replay Rewind
        inline const char* Replay_Rewind() const { return Get("Replay Rewind"); }

        // Replay Upload
        inline const char* Replay_Upload() const { return Get("Replay Upload"); }

        // Enable##framehistory_section label
        inline const char* Enable_framehistory_section_label() const { return Get("Enable##framehistory_section label"); }

        // Auto Reset label
        inline const char* Auto_Reset_label() const { return Get("Auto Reset label"); }

        // FrameHistory width label
        inline const char* FrameHistory_width_label() const { return Get("FrameHistory width label"); }

        // FrameHistory height label
        inline const char* FrameHistory_height_label() const { return Get("FrameHistory height label"); }

        // FrameHistory spacing label
        inline const char* FrameHistory_spacing_label() const { return Get("FrameHistory spacing label"); }

        // FrameHistory not enabled message
        inline const char* FrameHistory_not_enabled_message() const { return Get("FrameHistory not enabled message"); }

        // FrameHistory character load error
        inline const char* FrameHistory_character_load_error() const { return Get("FrameHistory character load error"); }

        // Language
        inline const char* Language() const { return Get("Language"); }

        // Language incomplete label
        inline const char* Language_incomplete_label() const { return Get("Language incomplete label"); }

        // Language selection help
        inline const char* Language_selection_help() const { return Get("Language selection help"); }

        // KoreWaTestoDakeDa
        inline const char* KoreWaTestoDakeDa() const { return Get("KoreWaTestoDakeDa"); }
};

