#!/usr/bin/env python3
import argparse
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

def sanitize_name(raw: str, existing: set) -> str:
    sanitized = re.sub(r"[^0-9A-Za-z_]+", "_", raw)
    sanitized = re.sub(r"_+", "_", sanitized).strip("_")
    if sanitized and sanitized[0].isdigit():
        sanitized = f"_{sanitized}"
    if not sanitized:
        sanitized = "Key"

    candidate = sanitized
    suffix = 1
    while candidate in existing:
        suffix += 1
        candidate = f"{sanitized}_{suffix}"
    existing.add(candidate)
    return candidate

def parse_resx(path: Path):
    tree = ET.parse(path)
    root = tree.getroot()
    for data in root.findall("data"):
        name = data.get("name")
        if not name or name.startswith("_"):
            continue
        yield name

def render_header(keys):
    lines = []
    lines.append("#pragma once")
    lines.append("// Auto-generated by tools/generate_localization_bindings.py. Do not edit by hand.")
    lines.append("// Source: resource/localization/Localization.resx")
    lines.append("#include <string>")
    lines.append("")
    lines.append("struct LocalizationKeysAccessor")
    lines.append("{")
    lines.append("        const char* Get(const std::string& key) const;")
    lines.append("")
    seen = set()
    for original in keys:
        method = sanitize_name(original, seen)
        escaped_comment = original.replace("\\", "\\\\").replace("\r", "").replace("\n", "\\n")
        escaped_literal = original.replace("\\", "\\\\").replace("\"", "\\\"").replace("\r", "").replace("\n", "\\n")
        lines.append(f"        // {escaped_comment}")
        lines.append(f"        inline const char* {method}() const {{ return Get(\"{escaped_literal}\"); }}")
        lines.append("")
    if lines[-1] == "":
        lines.pop()
    lines.append("};")
    lines.append("")
    return "\n".join(lines) + "\n"

def main():
    parser = argparse.ArgumentParser(description="Generate strongly-typed localization accessors from a .resx file.")
    parser.add_argument("--input", required=True, type=Path, help="Path to the fallback Localization.resx file.")
    parser.add_argument("--output", required=True, type=Path, help="Destination header path (e.g., src/Core/LocalizationKeys.autogen.h).")
    args = parser.parse_args()

    keys = list(parse_resx(args.input))
    if not keys:
        print("No keys found in resx", file=sys.stderr)
        return 1

    header = render_header(keys)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(header, encoding="utf-8")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
